server:
  port: 9093

logging:
  level:
    ROOT: info
    com.zjs.mj: debug
    com.zjs.mj.mapper: info

config:
  mj:
    plan: 4  #可选值1,2,3,4 分别对应(免费订阅，$10,$30,$60)用于调整同时提交的任务数量
    guild-id: 123456 #服务器id
    channel-id: 123456 #频道id
    user-token: 123456 #discord的用户token
    bot-token: 123456 #机器人token
    user-id: 123456 #midjourney用户id
    token: 123456 #midjourney用户token
  aliyun:
    accessKeyId:
    accessKeySecret:
  qq:
    login-type:  qrcode   #password or qrcode
    # MACOS  ANDROID_WATCH  ANDROID_PAD IPAD  ANDROID_PHONE五种协议
    #1. 登录方式选择password时五种协议都可以，推荐 ANDROID_PAD IPAD
    #2. 登录方式选择qrcode时，只能选择ANDROID_WATCH  MACOS 推荐ANDROID_WATCH
    protocol: ANDROID_WATCH
    account: 123456
    password: xxx  #当登录方式为qrcode时，该项可不用设置

spring:
  datasource:
    url: jdbc:mysql://db:3306/midjourney?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&socketTimeout=60000&connectTimeout=30000&serverTimezone=Asia/Shanghai
    username: root
    password: zhangsan  #和docker compose里mysql密码保持一致
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      max-lifetime: 1800000
      idle-timeout: 60000
      connection-timeout:   30000

