version: '3.1'

services:

  ipsec-vpn-server:
    image: hwdsl2/ipsec-vpn-server
    restart: always
    environment:
      - VPN_IPSEC_PSK=tianwanggaidihu
      - VPN_USER=root
      - VPN_PASSWORD=baotazhenheyao
      - VPN_ENABLE_MODP1024=yes
    volumes:
      - ikev2-vpn-data:/etc/ipsec.d
      - /lib/modules:/lib/modules:ro
      - ./vpn:/etc/ipsec.d/
    ports:
      - 500:500/udp
      - 4500:4500/udp
    privileged: true

volumes:
  ikev2-vpn-data: