server:
  port: 9093

logging:
  level:
    ROOT: info
    com.zjs.mj: debug
    com.zjs.mj.mapper: info



config:
  mj:
    plan: 4  #可选值1,2,3,4 分别对应(免费订阅，$10,$30,$60)用于调整同时提交的任务数量
    guild-id: 123456 #服务器id
    channel-id: 123456 #频道id
    user-token: 123456 #discord的用户token
    bot-token: 123456 #机器人token
    user-id: 123456 #midjourney用户id
    token: 123456 #midjourney用户token
  aliyun:
    accessKeyId:
    accessKeySecret:
  qq:
    account:     #qq号
#    password:   #扫码登录，不用配置

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/midjourney?useUnicode=true&characterEncoding=utf-8&useSSL=false&socketTimeout=60000&connectTimeout=30000&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      max-lifetime: 1800000
      idle-timeout: 60000
      connection-timeout:   30000
